services:
  db:
    image: postgres:17-alpine
    container_name: notes_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: note_service
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/notes_db
      - PORT=${PORT:-8080}
    depends_on:
      - db

volumes:
  postgres-data:
